language: perl6

perl6:
    - '2021.03'
    - latest

install:
    - rakudobrew build-zef
    # Explicitly install HEAD of Cro::Core, Cro::TLS, and Cro::HTTP
    - zef install https://github.com/croservices/cro-core/archive/master.zip
    - zef install https://github.com/croservices/cro-tls/archive/master.zip
    - zef install https://github.com/croservices/cro-http/archive/master.zip
    - zef --debug --deps-only install .
